export enum Intent {
  WELCOME_SCREEN = 'WELCOME_SCREEN',
  HELLO = 'HELLO',
  GOODBYE = 'GOODBYE',
  SHOW_MENU = 'SHOW_MENU',
  SHOW_LIST_ITEMS = 'SHOW_LIST_ITEMS',
  SHOW_ITEM = 'SHOW_ITEM',
  ADD_ORDER = 'ADD_ORDER',
  CHANGE_ORDER = 'CHANGE_ORDER',
  REMOVE_ORDER = 'REMOVE_ORDER',
  SHOW_ORDER = 'SHOW_ORDER',
  CHECKOUT = 'CHECKOUT',
  SMALLTALK = 'SMALLTALK',
}
